upstream rental_service {
    server rental-service:8081;
}

upstream payment_service {
    server payment-service:8082;
}

upstream damage_service {
    server damage-penalty-service:8083;
}

server {
    listen 8000;

    location /api/rentals {
        proxy_pass http://rental_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/payments {
        proxy_pass http://payment_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/invoices {
        proxy_pass http://payment_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/damage-reports {
        proxy_pass http://damage_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/penalties {
        proxy_pass http://damage_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
